import {
  Home,
  About,
  Contact,
  Legal,
  Login,
  CreatePassword,
  Services,
  Items,
  ProductDescription,
  Cart,
  Signup,
  Brands,
  EmailVerify,
  ForgetPassword,
  Ledger,
  OrderLines,
  Privacy,
  Terms,
  UploadImage
} from "../Pages";

const AllRoutes = [
  { path: "/", component: Home },
  { path: "/About", component: About },
  { path: "/Contact", component: Contact },
  { path: "/Legal", component: Legal },
  { path: "/Privacy", component: Privacy },
  { path: "/Login", component: Login },
  { path: "/Signup", component: Signup },
  { path: "/Services", component: Services },
  { path: "/Products/:ptcategory?/:Category?/:subCategory?/:brands?", component: Items },
  { path: "/Product/:ptcategory?/:brands?", component: Items },
  { path: "/ProductsDescription/:id", component: ProductDescription },
  { path: "/Cart", component: Cart },
  { path: "/Brands", component: Brands },
  { path: "/ForgetPassword", component: EmailVerify },
  { path: "/VerifyEmail", component: CreatePassword },
  { path: "/customers/reset-password/:id/:token", component: ForgetPassword },
  { path: "/Ledger", component: Ledger },
  { path: "/OrderLines/:id", component: OrderLines },
  { path: "/Terms", component: Terms },
  { path: "/UploadImage", component: UploadImage },
];

export { AllRoutes };
